server:
  port: 9091
  address: 127.0.0.1
  servlet:
    context-path: /my_retail
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
      fail-on-missing-creator-properties: true
    time-zone: UTC
myretail:
  partner-apis:
    apiKey: TOKENONE
    authorization-token: Bearer `sometoken`
    prices:
      base-url: http://localhost:9091/my_retail
      path: /v1/attributes/products/{productId}
      timeout: 10
    attributes:
      baseUrl: http://localhost:9091/my_retail
      getPath: /v1/prices/products/{productId}
      timeout: 10
  security:
    valid-api-keys:
      - TOKENONE
      - TOKENTWO
      - TOKENTHREE
    valid-authorization-token: Bearer `sometoken`

