server:
  port: 9091
  address: 127.0.0.1
  servlet:
    context-path: /my_retail
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
      fail-on-missing-creator-properties: true
    time-zone: UTC
  data:
    mongodb:
      uri: mongodb://username:password@localhost:27080/prices?authSource=admin
myretail:
  partner-apis:
    api-key: TOKENONE
    authorization-token: Bearer `sometoken`
    prices:
      url: http://localhost:9091/my_retail/v1/prices/products/
      timeout: 10
    attributes:
      url: http://localhost:9091/my_retail/v1/attributes/products/
      timeout: 10
  security:
    valid-api-keys:
      - TOKENONE
      - TOKENTWO
      - TOKENTHREE
    valid-authorization-token: Bearer `sometoken`

