swagger: '2.0'
info:
  version: '1.0'
  description: My Retail Products Price Core API
  title: My Retail Products Price Core API
host: localhost:9091
basePath: /my_retail
tags:
  - name: prices-controller
    description: Prices Controller
paths:
  /v1/products/{productId}/prices:
    get:
      tags:
        - prices-controller
      summary: getPricesByProductId
      operationId: getPricesByProductIdUsingGET
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          description: productId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PricesDocument'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  AllPrices:
    type: object
    properties:
      current_price:
        $ref: '#/definitions/Price'
      initial_price:
        $ref: '#/definitions/Price'
      regular_price:
        $ref: '#/definitions/Price'
    title: AllPrices
  Price:
    type: object
    required:
      - currency_code
      - value
    properties:
      currency_code:
        type: string
      value:
        type: number
        format: double
    title: Price
  PricesDocument:
    type: object
    required:
      - prices
      - product_id
    properties:
      prices:
        $ref: '#/definitions/AllPrices'
      product_id:
        type: integer
        format: int64
    title: PricesDocument
