swagger: '2.0'
info:
  description: MyRetail Details Aggregation API
  title: MyRetail Details Aggregation API
  version: '1.0'
host: 'localhost:9090'
basePath: /my_retail
tags:
  - name: details-controller
    description: Details Controller
paths:
  '/v1/products/{product_id}/locations/{location_id}/details':
    get:
      tags:
        - details-controller
      summary: getDetailsByProductIdAndLocationId
      operationId: getDetailsByProductIdAndLocationIdUsingGET
      produces:
        - application/json
      parameters:
        - name: "key"
          in: "query"
          description: Valid api key.
          required: true
          type: "string"
        - name: "authorization"
          in: "header"
          description: Valid authorization bearer token.
          required: true
          type: "string"
        - name: product_id
          in: path
          description: product id
          required: true
          type: integer
        - name: location_id
          in: path
          description: location id
          required: true
          type: integer
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DetailsResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error

definitions:
  DetailsResponse:
    type: object
    required:
      - product_id
      - location_id
      - name
      - current_price
    properties:
      product_id:
        type: integer
      location_id:
        type: integer
      name:
        type: string
      current_price:
        $ref: '#/definitions/Price'
    title: Details Response
  Price:
    type: object
    required:
      - value
      - currency_code
    properties:
      value:
        type: number
      currency_code:
        type: string
    title: Price
